name: Update Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update_data:
    name: Update Data
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependecies
      run: pip install -r requirements.txt

    - name: Get updated data from Google Docs
      run: /bin/bash download_updated_data.sh

    - name: Update the data
      run: python -m app

    - name: Update upstream
      uses: stefanzweifel/git-auto-commit-action@v4
